tst_rast: tst_rast.o raster.o rast_asm.o font.o bitmap.o
	cc68x -g tst_rast.o raster.o rast_asm.o font.o bitmap.o -o tst_rast

tst_rast.o: tst_rast.c raster.h font.h
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

font.o: font.c font.h
	cc68x -g -c font.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

bitmap.o: bitmap.c bitmap.h font.h
	cc68x -g -c bitmap.c
